### PR TITLE
Removes the email service health check

### PR DESCRIPTION
**Pull request by GlynnPhillips**
This was sending a lot of requests (80 requests per minute) to the email
service and the uuid in the request didn't exist in the email service
anyway. So it wasn't adding much value to us and causing the email team
unwated load.

### CODE REVIEW

**Review by leafrogers — APPROVED** [review]
❤️ ❤️ ❤️

**Comment by leafrogers** [comment]
Oh hang on, looks like it’s [calling it elsewhere](https://github.com/Financial-Times/session-user-data-service/search?q=%22services%2Femail%22&unscoped_q=%22services%2Femail%22) too for some reason 🤷‍♂

**Comment by GlynnPhillips** [comment]
Good spot, I will remove those as well tomorrow

**Comment by GlynnPhillips** [comment]
@keirog I have removed all the healthcheck instances of this as its low impact to do so. Other changes are more risky and as this is going to be deprecated very soon I am hoping you might be able to hold on a little longer?

**Review by ker-an — APPROVED** [review]

**Comment by leafrogers** [comment]
Ace! This was the only change I was after, so thank you most kindly 😊 🙇

**Pull request merged**
